2 add user management
your-own-stuff/yos-web pull request #4
Opened 2024-03-25 23:36 UTC by simpros

Added basic admin functionality

2024-03-25 23:56 UTC, Jan-Ka requested changes
Please see comments ✨

2024-03-25 23:56 UTC, Jan-Ka commented on src/routes/(authenticated)/+layout.svelte
> +				<enhanced:img src="../../assets/hausi.svg" class="h-10 w-10" />
Would be better if you'd move `hausi.svg` into a svelte component. You can use this code: https://github.com/your-own-stuff/page/blob/main/src/lib/reusables/logo.svelte

2024-03-25 23:56 UTC, Jan-Ka commented on src/lib/create-pb-admin.ts
> +	const pbAdmin = new PocketBase('http://127.0.0.1:8090') as YosPocketBase;
Should read the Backend API from `.env` file

2024-03-25 23:56 UTC, Jan-Ka commented on src/lib/create-pb-admin.ts
> +	await pbAdmin.admins.authWithPassword(ADMIN_EMAIL, ADMIN_PASSWORD);
This can't be a good idea.

2024-03-26 06:36 UTC, simpros commented on src/routes/(authenticated)/+layout.svelte
> +				<enhanced:img src="../../assets/hausi.svg" class="h-10 w-10" />
Done ✔️

2024-03-26 06:42 UTC, simpros commented on src/lib/create-pb-admin.ts
> +	await pbAdmin.admins.authWithPassword(ADMIN_EMAIL, ADMIN_PASSWORD);
![CleanShot 2024-03-26 at 07 38 01](https://github.com/your-own-stuff/yos-web/assets/38320875/0c261596-ccff-478a-b44c-fd63d6a1fdd1)

It is not a problem, as the pbAdmin can only be accessed on the server side - sveltekit will prevent it from building if any of the private env variables would leak into client-side code. The other option would be to update the access rights 😅

2024-03-26 06:43 UTC, simpros commented on src/lib/create-pb-admin.ts
> +	const pbAdmin = new PocketBase('http://127.0.0.1:8090') as YosPocketBase;
Done ✔️

2024-03-26 08:22 UTC, Jan-Ka approved these changes
LGTM

2024-03-26 08:30 UTC, merged